---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: templateservicebrokers.openshift.io
spec:
  group: openshift.io
  names:
    kind: TemplateServiceBroker
    listKind: TemplateServiceBrokerList
    plural: templateservicebrokers
    singular: templateservicebroker
  scope: Namespaced
  version: v1alpha1
