---
- name: template-service-broker-operator
  hosts: localhost
  become: false
  gather_facts: false
  connection: local
  vars:
    state: present
    broker_name: "{{ meta.name }}"
    broker_namespace: "{{ meta.namespace }}"
    broker_image: "{{ lookup('env', 'IMAGE') }}"
  tasks:
    - name: Validation
      assert:
        that: broker_name and broker_namespace and broker_image
        fail_msg: >
          broker_name broker_namespace broker_image must be defined
          The IMAGE environment variable must provide the broker's image name
          and should be specified in the operator's deployment specification.
    - name: Run template-service-broker role
      include_role:
        name: template-service-broker
