---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ broker_name }}-{{ broker_namespace }}"
rules:
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.openshift.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - template.openshift.io
  resources:
  - brokertemplateinstances
  verbs:
  - create
  - delete
  - get
  - update
- apiGroups:
  - template.openshift.io
  resources:
  - brokertemplateinstances/finalizers
  verbs:
  - update
- apiGroups:
  - template.openshift.io
  resources:
  - templateinstances
  verbs:
  - assign
  - create
  - delete
  - get
- apiGroups:
  - template.openshift.io
  resources:
  - templates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - routes
  verbs:
  - get
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
