---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: True
    ansible_connection_options: {}
lint:
  name: yamllint
  enabled: False
platforms:
- name: cluster
  groups:
  - k8s
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        namespace: ${TEST_NAMESPACE:-osdk-test}
        csv_version: ${CSV_VERSION:-4.3}
        deploy_dir: ${MOLECULE_PROJECT_DIRECTORY}/deploy
  lint:
    name: ansible-lint
    enabled: False
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
    K8S_AUTH_KUBECONFIG: ${KUBECONFIG}
    IMAGE_FORMAT: ${IMAGE_FORMAT:-quay.io/openshift/origin-$component}
scenario:
  name: cluster-olm
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
